### ISSUE TITLE
希望对这个项目的制作要求有更明确的说明。

### ISSUE THREAD

**Issue by HenryzhaoH** [BUPT-SCSS-BuryLove/SingerSignUp#1]
唉嘿！

**Comment by Yang-Linqing** [comment]
三院合办的歌手大赛报名系统。仅限报名和修改报名信息的功能。包括基本信息填写和bgm上传。服务器买腾讯云。不给学校的服务器。域名大概也没有。用户身份识别用微信。 @carol233 做前端， 我做后端。

**Comment by Yang-Linqing** [comment]
@carol233 能不能有时间把详细信息写到wiki里面
